services:
  postgres:
    container_name: postgres
    build:
      dockerfile: db/Dockerfile
      context: ./
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - logs:/logs:z
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  logs:
